
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    # volumes:
    #   - matomo:/var/www/html:ro
    #   - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80